spring:
  application:
    name: tissenza-backend
  profiles:
    active: dev

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info

tissenza:
  app:
    jwtSecret: mySuperSecretKeyForJWTTokenGenerationThatIsLongEnoughForHS256Algorithm
    jwtExpirationMs: 86400000